input_path: \var\shepherd\recordings\hrv.h5
output_path: \var\shepherd\recordings
output_compression: 1
start_time: 2022-12-13 14:15:16
duration: 0:10:00
enable_io: true
voltage_aux: 3.3
virtual_source:
  name: bq25570
  enable_boost: true
  enable_buck: true
  harvester:
    name: mppt_bq_solar
    datatype: DTypeEnum.ivsample
    current_limit_uA: 5.0
    setpoint_n: 0.76
    interval_ms: 16000.0
    duration_ms: 256.0
  V_input_max_mV: 5100.0
  I_input_max_mA: 100.0
  C_intermediate_uF: 33.0
  V_intermediate_init_mV: 3600.0
  V_intermediate_enable_threshold_mV: 3000.0
  V_intermediate_disable_threshold_mV: 2400.0
  interval_check_thresholds_ms: 64.0
  V_pwr_good_enable_threshold_mV: 3000.0
  V_pwr_good_disable_threshold_mV: 2500.0
  immediate_pwr_good_signal: false
  V_input_boost_threshold_mV: 100.0
  V_intermediate_max_mV: 5500.0
  LUT_input_efficiency:
  - - 0.01
    - 0.01
    - 0.02
    - 0.05
    - 0.1
    - 0.15
    - 0.15
    - 0.2
    - 0.25
    - 0.3
    - 0.3
    - 0.35
  - - 0.1
    - 0.2
    - 0.3
    - 0.4
    - 0.5
    - 0.55
    - 0.56
    - 0.57
    - 0.58
    - 0.59
    - 0.6
    - 0.61
  - - 0.2
    - 0.4
    - 0.5
    - 0.6
    - 0.65
    - 0.66
    - 0.67
    - 0.68
    - 0.69
    - 0.7
    - 0.71
    - 0.72
  - - 0.35
    - 0.55
    - 0.65
    - 0.71
    - 0.73
    - 0.74
    - 0.75
    - 0.75
    - 0.76
    - 0.77
    - 0.77
    - 0.78
  - - 0.45
    - 0.65
    - 0.7
    - 0.73
    - 0.75
    - 0.77
    - 0.78
    - 0.79
    - 0.8
    - 0.81
    - 0.81
    - 0.82
  - - 0.5
    - 0.7
    - 0.74
    - 0.76
    - 0.78
    - 0.79
    - 0.8
    - 0.81
    - 0.82
    - 0.83
    - 0.83
    - 0.84
  - - 0.52
    - 0.73
    - 0.76
    - 0.78
    - 0.8
    - 0.81
    - 0.82
    - 0.83
    - 0.84
    - 0.85
    - 0.85
    - 0.86
  - - 0.53
    - 0.75
    - 0.77
    - 0.79
    - 0.81
    - 0.82
    - 0.83
    - 0.84
    - 0.85
    - 0.86
    - 0.86
    - 0.87
  - - 0.55
    - 0.77
    - 0.78
    - 0.8
    - 0.82
    - 0.83
    - 0.85
    - 0.86
    - 0.87
    - 0.87
    - 0.87
    - 0.88
  - - 0.56
    - 0.78
    - 0.79
    - 0.81
    - 0.83
    - 0.85
    - 0.87
    - 0.88
    - 0.88
    - 0.88
    - 0.88
    - 0.89
  - - 0.58
    - 0.79
    - 0.8
    - 0.82
    - 0.84
    - 0.86
    - 0.88
    - 0.89
    - 0.89
    - 0.89
    - 0.89
    - 0.9
  - - 0.6
    - 0.8
    - 0.81
    - 0.83
    - 0.85
    - 0.87
    - 0.89
    - 0.9
    - 0.9
    - 0.9
    - 0.9
    - 0.9
  LUT_input_V_min_log2_uV: 17
  LUT_input_I_min_log2_nA: 13
  V_output_mV: 3000.0
  LUT_output_efficiency:
  - 0.4
  - 0.5
  - 0.6
  - 0.73
  - 0.82
  - 0.86
  - 0.88
  - 0.9
  - 0.91
  - 0.92
  - 0.93
  - 0.92
  LUT_output_I_min_log2_nA: 10
gpio_logging:
  log_gpio: true
  decode_uart: true
  baudrate_uart: 9600
sys_logging:
  log_dmesg: true
