---

- name: Enable djangos secret-key as envvar
  ansible.builtin.lineinfile:
    dest: '/home/{{ ansible_user }}/.bashrc'
    regex: '^.*export DJANGO_SECRET_KEY.*$'
    line: "export DJANGO_SECRET_KEY={{django_secret_key}}"
  notify: restart device
  
# TODO: 
# - enable django-server
# - is this usable without login? 