---
# proposed by helpdesk - login-server and dgw share home-directory
# hard to do as a role because of 

- name: add datastorage to server
  hosts: all
  become: true
  gather_facts: no
  
#  vars:
#    key_server: login.zih.tu-dresden.de
#    ds_server: dgw.zih.tu-dresden.de
#    ds_path_remote: /svm/vs-grp04/shepherdDS
#    ds_path_local: /mnt/shp_ds/
  
#  vars_prompt:
#    - name: ds_user
#      prompt: "Please provide ZIH username with access to storage"
#      private: no
#    - name: ds_password
#      prompt: "users password"
#      private: yes

  tasks:

  - fail: msg="The variable '{{item}}' is not defined"
    when: (item is defined) and (item|length > 0) 
    with_items:
    - key_server
    - data_server
    - data_path_remote
    - data_path_local
    - zih_user
    - zih_password

  - name: Check if keypair is present on shepherd-server
    stat:
      path: /home/{{ ansible_user }}/.ssh/id_rsa.pub
    register: key_file
        
  - name: Generate fresh key-pair (if needed)
    ansible.builtin.shell: ssh-keygen -q -t rsa -N "" -C cfaed_nes_shepherd_server
    when: not key_file.exits
    become: no

  - name: APT - Install required packages
    apt:
      name: ["sshfs", "sshpass"] 
      state: present
      update_cache: yes
  
  - name: authorize shp-server with key-server
    ansible.builtin.shell: sshpass -p "{{zih_password}}" ssh-copy-id {{zih_user}}@{{key_server}}

  - name: create mount-directory
    ansible.builtin.file:
      path: {{data_path_local}}
      owner: {{ansible_user}}
  
  - name: enable automatic mounting
    lineinfile:
      dest: '/home/{{ ansible_user }}/.bashrc'
      regex: '^.*sshfs.*$'
      line: "sshfs {{zih_user}}@{{data_server}}:{{data_path_remote}} {{data_path_local}}

  - name: restart device
    shell: sleep 2 && shutdown -r now "Ansible restart"
    async: 1
    poll: 0
    ignore_errors: true

  - name: waiting to come back
    wait_for_connection:
      delay: 15
      timeout: 300
    become: no
    