---
- name: Install Server - Role-based
  hosts: all
  become: true

  pre_tasks:

    - name: Get time and date from ansible controller
      ansible.builtin.command: 'date -u +"%Y-%m-%dT%H:%M:%SZ"'
      delegate_to: localhost
      changed_when: false
      register: local_time
      become: false
    - name: Set correct time
      ansible.builtin.command: "date -s {{ local_time.stdout }}"
      changed_when: true

    - name: Update SSL-Certificates
      ansible.builtin.command: 'update-ca-certificates -f -v'
      changed_when: true

    - name: APT - Upgrade all packages to the latest version
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true

- name: Main software for Shepherd Server
  hosts: server
  become: true
  roles:
    - apt-automatic
    - ntp-client
    - secure-host
    - django-server

- name: Integrate Datastorage, Update System and cleanup
  hosts: server
  become: true

  tasks:


    - name: Integrate datastorage
      ansible.builtin.include_tasks:
        file: "setup_zih_datastorage.yml"

    - name: Clean apt-caches - A
      ansible.builtin.apt:
        autoremove: true
    - name: Clean apt-caches - B
      ansible.builtin.apt:
        autoclean: true
    - name: Clean apt-caches - C
      ansible.builtin.apt:
        clean: true



